import { useRouteRuntime, type AdminUserForm } from "../../app/routeRuntime";

export default function AdminRoute() {
  const { admin } = useRouteRuntime();
  const roles = admin.roles.length ? admin.roles : [{ id: 1, name: "Administrator" }];
  const textField = (label: string, name: keyof AdminUserForm, mode: "create" | "edit", type = "text") => { const form = mode === "create" ? admin.createForm : admin.editForm; const update = mode === "create" ? admin.updateCreate : admin.updateEdit; return <label>{label}<input type={type} value={String(form[name] ?? "")} onChange={(event) => update(name, event.target.value)} /></label>; };
  return <section className="grid single-col"><article className="panel admin-center-panel"><div className="panel-head"><h2>Admin Center</h2><p>Identity, roles, user lifecycle, and password administration.</p></div>
    <article className="panel"><h3>Session</h3>{admin.sessionUser ? <p className="subtitle">Signed in as {admin.sessionUser.username} ({admin.sessionUser.role_name})</p> : null}{admin.sessionError ? <p className="error">{admin.sessionError}</p> : null}</article>
    <article className="panel"><div className="panel-head"><h3>Users</h3><button className="button-secondary" type="button" onClick={admin.refresh} disabled={!admin.authenticated || admin.loading}>Refresh</button></div>{admin.error ? <p className="error">{admin.error}</p> : null}{admin.loading ? <p className="subtitle">Loading users and roles...</p> : null}<div className="table-wrap table-wrap-scroll-x"><table><thead><tr><th>ID</th><th>Username</th><th>Email</th><th>Role</th><th>Status</th><th>Active</th><th>Actions</th></tr></thead><tbody>{admin.users.map((row, index) => <tr key={row.id || index}><td>{row.id || "-"}</td><td>{row.username || "-"}</td><td>{row.email || "-"}</td><td>{row.role_name || row.role_id || "-"}</td><td>{row.status || "-"}</td><td>{row.is_active ? "yes" : "no"}</td><td><button type="button" className="button-secondary" onClick={() => admin.selectUser(row)}>Edit</button></td></tr>)}{!admin.users.length && !admin.loading ? <tr><td colSpan={7}>No users returned yet. Refresh or create a user.</td></tr> : null}</tbody></table></div></article>
    <article className="panel"><h3>Create User</h3><form className="form" onSubmit={admin.create}><div className="filter-grid">{textField("Username", "username", "create")}{textField("Email", "email", "create")}{textField("First Name", "first_name", "create")}{textField("Last Name", "last_name", "create")}</div><div className="filter-grid">{textField("Password", "password", "create", "password")}<label>Role<select value={admin.createForm.role_id} onChange={(event) => admin.updateCreate("role_id", Number(event.target.value))}>{roles.map((role) => <option key={role.id} value={role.id}>{role.name}</option>)}</select></label><label>Status<input value={admin.createForm.status} onChange={(event) => admin.updateCreate("status", event.target.value)} /></label><label>Active<select value={String(admin.createForm.is_active)} onChange={(event) => admin.updateCreate("is_active", event.target.value === "true")}><option value="true">true</option><option value="false">false</option></select></label></div><button className="button-primary" type="submit" disabled={!admin.authenticated || admin.loading}>Create User</button></form></article>
    <article className="panel"><h3>Modify User</h3><form className="form" onSubmit={admin.update}><div className="filter-grid"><label>User ID<input value={admin.editForm.id || ""} readOnly /></label><label>Username<input value={admin.editForm.username} readOnly /></label>{textField("Email", "email", "edit")}<label>Role<select value={admin.editForm.role_id} onChange={(event) => admin.updateEdit("role_id", Number(event.target.value))}>{roles.map((role) => <option key={role.id} value={role.id}>{role.name}</option>)}</select></label></div><div className="filter-grid">{textField("First Name", "first_name", "edit")}{textField("Last Name", "last_name", "edit")}<label>Status<select value={admin.editForm.status} onChange={(event) => admin.updateEdit("status", event.target.value)}>{["active", "inactive", "suspended"].map((value) => <option key={value} value={value}>{value}</option>)}</select></label><label>Active<select value={String(admin.editForm.is_active)} onChange={(event) => admin.updateEdit("is_active", event.target.value === "true")}><option value="true">true</option><option value="false">false</option></select></label></div><button className="button-primary" type="submit" disabled={!admin.authenticated || admin.loading || !admin.editForm.id}>Update User</button></form></article>
    <article className="panel"><h3>Reset Password</h3><form className="form" onSubmit={admin.reset}><div className="filter-grid"><label>User ID<input value={admin.resetUserId || ""} readOnly /></label><label>New Password<input type="password" value={admin.resetPassword} onChange={(event) => admin.setResetPassword(event.target.value)} /></label></div><button className="button-primary" type="submit" disabled={!admin.authenticated || admin.loading || !admin.resetUserId || !admin.resetPassword.trim()}>Reset Password</button></form></article>
  </article></section>;
}
