-- Bus-agnostic metadata event store and incident projection for scalable ops analytics.

CREATE TABLE IF NOT EXISTS incident_events (
    id CHAR(32) PRIMARY KEY,
    incident_id CHAR(32) NOT NULL,
    alert_id CHAR(32),
    trace_id VARCHAR(128),
    correlation_id VARCHAR(255),
    causation_id VARCHAR(255),
    parent_event_id CHAR(32),
    tenant_id VARCHAR(128) NOT NULL DEFAULT 'default',
    service VARCHAR(128) NOT NULL,
    environment VARCHAR(64) NOT NULL,
    region VARCHAR(128),
    team VARCHAR(128),
    severity VARCHAR(32),
    status VARCHAR(64),
    event_type VARCHAR(128) NOT NULL,
    event_stage VARCHAR(64) NOT NULL,
    risk_tier VARCHAR(32),
    execution_mode VARCHAR(32),
    requires_approval BOOLEAN,
    policy_version VARCHAR(64),
    policy_reason TEXT,
    confidence DOUBLE,
    model_provider VARCHAR(64),
    model_name VARCHAR(128),
    transport_provider VARCHAR(32) NOT NULL,
    transport_channel VARCHAR(128) NOT NULL,
    transport_partition INTEGER,
    transport_offset BIGINT,
    transport_delivery_tag VARCHAR(128),
    idempotency_key VARCHAR(255),
    fingerprint VARCHAR(255),
    payload JSON NOT NULL,
    created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    KEY idx_incident_events_incident_time (incident_id, created_at DESC),
    KEY idx_incident_events_service_status_time (service, status, created_at DESC),
    KEY idx_incident_events_trace (trace_id),
    KEY idx_incident_events_corr (correlation_id),
    KEY idx_incident_events_transport (transport_provider, transport_channel, created_at DESC),
    UNIQUE KEY uq_incident_events_idempotency (transport_provider, idempotency_key)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS incident_projections (
    incident_id CHAR(32) PRIMARY KEY,
    alert_id CHAR(32),
    trace_id VARCHAR(128),
    tenant_id VARCHAR(128) NOT NULL DEFAULT 'default',
    service VARCHAR(128) NOT NULL,
    environment VARCHAR(64) NOT NULL,
    severity VARCHAR(32),
    status VARCHAR(64) NOT NULL,
    owner VARCHAR(128),
    risk_tier VARCHAR(32),
    execution_mode VARCHAR(32),
    requires_approval BOOLEAN,
    policy_version VARCHAR(64),
    policy_reason TEXT,
    transport_provider VARCHAR(32),
    latest_event_id CHAR(32),
    latest_event_type VARCHAR(128),
    latest_event_at DATETIME(6),
    first_seen_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    projection_payload JSON NOT NULL,
    KEY idx_incident_projections_status (status),
    KEY idx_incident_projections_service_severity (service, severity),
    KEY idx_incident_projections_risk_mode (risk_tier, execution_mode),
    KEY idx_incident_projections_updated (updated_at DESC)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
