-- Phase 1 canonical ticket and durable ingestion foundation (MySQL 8+).
CREATE TABLE IF NOT EXISTS canonical_tickets (
    ticket_id VARCHAR(128) PRIMARY KEY,
    tenant_id VARCHAR(128) NOT NULL,
    schema_version VARCHAR(16) NOT NULL DEFAULT '1.0',
    source VARCHAR(64) NOT NULL,
    source_reference VARCHAR(512) NOT NULL,
    title VARCHAR(512) NOT NULL,
    description TEXT NOT NULL,
    category VARCHAR(128) NOT NULL,
    subcategory VARCHAR(128) NOT NULL,
    severity ENUM('P1', 'P2', 'P3', 'P4') NOT NULL,
    priority SMALLINT UNSIGNED NOT NULL,
    status VARCHAR(64) NOT NULL,
    affected_service VARCHAR(255) NOT NULL,
    environment VARCHAR(64) NOT NULL,
    customer_impact TEXT NOT NULL,
    business_impact TEXT NOT NULL,
    correlation_id VARCHAR(128) NOT NULL,
    duplicate_of VARCHAR(128),
    confidence DECIMAL(5,4) NOT NULL,
    evidence JSON NOT NULL,
    assigned_team VARCHAR(255),
    assigned_engineer VARCHAR(255),
    related_ticket_ids JSON NOT NULL,
    noise BOOLEAN NOT NULL DEFAULT FALSE,
    false_positive BOOLEAN NOT NULL DEFAULT FALSE,
    sla_deadline DATETIME(6),
    escalation_required BOOLEAN NOT NULL DEFAULT FALSE,
    audit_metadata JSON NOT NULL,
    created_at DATETIME(6) NOT NULL,
    updated_at DATETIME(6) NOT NULL,
    UNIQUE KEY uq_canonical_ticket_source (tenant_id, source, source_reference),
    KEY idx_canonical_ticket_queue (tenant_id, status, severity, updated_at DESC),
    KEY idx_canonical_ticket_correlation (tenant_id, correlation_id),
    CONSTRAINT fk_canonical_ticket_duplicate FOREIGN KEY (duplicate_of) REFERENCES canonical_tickets(ticket_id),
    CONSTRAINT chk_ticket_priority CHECK (priority BETWEEN 1 AND 100),
    CONSTRAINT chk_ticket_confidence CHECK (confidence BETWEEN 0 AND 1)
);

CREATE TABLE IF NOT EXISTS ingestion_events (
    event_id CHAR(36) PRIMARY KEY,
    tenant_id VARCHAR(128) NOT NULL,
    connector_id VARCHAR(128) NOT NULL,
    source VARCHAR(64) NOT NULL,
    source_event_id VARCHAR(512) NOT NULL,
    idempotency_key CHAR(64) NOT NULL,
    correlation_id VARCHAR(128) NOT NULL,
    schema_version VARCHAR(16) NOT NULL,
    status ENUM('received', 'validated', 'published', 'retrying', 'dead_lettered') NOT NULL,
    attempt_count INT UNSIGNED NOT NULL DEFAULT 0,
    payload_ref VARCHAR(1024) NOT NULL,
    payload_sha256 CHAR(64) NOT NULL,
    error_code VARCHAR(128),
    error_detail TEXT,
    next_attempt_at DATETIME(6),
    received_at DATETIME(6) NOT NULL,
    updated_at DATETIME(6) NOT NULL,
    UNIQUE KEY uq_ingestion_replay (tenant_id, connector_id, idempotency_key),
    KEY idx_ingestion_retry (status, next_attempt_at),
    KEY idx_ingestion_correlation (tenant_id, correlation_id)
);

CREATE TABLE IF NOT EXISTS connector_definitions (
    connector_id VARCHAR(128) PRIMARY KEY,
    tenant_id VARCHAR(128) NOT NULL,
    connector_type VARCHAR(64) NOT NULL,
    display_name VARCHAR(255) NOT NULL,
    enabled BOOLEAN NOT NULL DEFAULT FALSE,
    config JSON NOT NULL,
    credential_reference VARCHAR(1024) NOT NULL,
    auth_type VARCHAR(64) NOT NULL,
    max_payload_bytes INT UNSIGNED NOT NULL,
    health_status VARCHAR(32) NOT NULL DEFAULT 'unknown',
    last_health_check_at DATETIME(6),
    created_by VARCHAR(255) NOT NULL,
    created_at DATETIME(6) NOT NULL,
    updated_at DATETIME(6) NOT NULL,
    UNIQUE KEY uq_connector_name (tenant_id, display_name),
    KEY idx_connector_health (tenant_id, enabled, health_status)
);

