CREATE TABLE IF NOT EXISTS service_onboarding_profiles (
  id CHAR(32) PRIMARY KEY,
  tenant_id VARCHAR(128) NOT NULL,
  project_id VARCHAR(128) NOT NULL,
  service_id VARCHAR(128) NOT NULL,
  environment VARCHAR(64) NOT NULL,
  template_id VARCHAR(128) NOT NULL,
  onboarding_state VARCHAR(32) NOT NULL DEFAULT 'DRAFT',
  business_criticality VARCHAR(32) NOT NULL DEFAULT 'medium',
  owners JSON NOT NULL,
  support_groups JSON NOT NULL,
  connection_ids JSON NOT NULL,
  telemetry JSON NOT NULL,
  slos JSON NOT NULL,
  business_kpis JSON NOT NULL,
  change_sources JSON NOT NULL,
  knowledge_refs JSON NOT NULL,
  diagnostic_capabilities JSON NOT NULL,
  remediation_capabilities JSON NOT NULL,
  validation_rules JSON NOT NULL,
  escalation_policies JSON NOT NULL,
  hitl_policy JSON NOT NULL,
  dependencies JSON NOT NULL,
  metadata JSON NOT NULL,
  version INT NOT NULL DEFAULT 1,
  created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  UNIQUE KEY uq_service_onboarding_scope (tenant_id, project_id, service_id, environment),
  KEY idx_service_onboarding_state (tenant_id, project_id, environment, onboarding_state),
  KEY ix_service_onboarding_profiles_tenant_id (tenant_id),
  KEY ix_service_onboarding_profiles_project_id (project_id),
  KEY ix_service_onboarding_profiles_service_id (service_id),
  KEY ix_service_onboarding_profiles_environment (environment),
  KEY ix_service_onboarding_profiles_template_id (template_id),
  KEY ix_service_onboarding_profiles_business_criticality (business_criticality)
);
