CREATE TABLE IF NOT EXISTS object_storage_metadata (
  id CHAR(32) NOT NULL,
  tenant_id VARCHAR(128) NOT NULL DEFAULT 'default',
    object_key VARCHAR(512) NOT NULL,
  object_uri VARCHAR(1536) NOT NULL,
  object_type VARCHAR(64) NOT NULL,
  application VARCHAR(255) NULL,
  environment VARCHAR(64) NULL,
  incident_id CHAR(32) NULL,
  alert_id CHAR(32) NULL,
  source VARCHAR(128) NULL,
  occurrence_at DATETIME(6) NULL,
  ingested_at DATETIME(6) NULL,
  size_bytes BIGINT NOT NULL,
  checksum_sha256 VARCHAR(64) NOT NULL,
  retention_policy VARCHAR(64) NOT NULL DEFAULT 'standard',
  security_classification VARCHAR(64) NOT NULL DEFAULT 'internal',
  processing_status VARCHAR(32) NOT NULL DEFAULT 'stored',
  metadata_payload JSON NOT NULL,
  created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  PRIMARY KEY (id),
  UNIQUE KEY uq_object_storage_key (object_key),
  KEY idx_object_storage_tenant (tenant_id),
  KEY idx_object_storage_scope_created (application, environment, created_at),
  KEY idx_object_storage_relation (incident_id, alert_id),
  KEY idx_object_storage_status_created (processing_status, created_at),
  KEY idx_object_storage_checksum (checksum_sha256)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
