CREATE TABLE IF NOT EXISTS canonical_evidence (
  evidence_id VARCHAR(68) NOT NULL PRIMARY KEY,
  requirement_id CHAR(36) NOT NULL,
  tenant_id VARCHAR(128) NOT NULL,
  incident_id CHAR(36) NOT NULL,
  category VARCHAR(32) NOT NULL,
  source_id VARCHAR(512) NOT NULL,
  connector VARCHAR(128) NOT NULL,
  source_reference VARCHAR(1536) NOT NULL,
  service VARCHAR(255) NULL,
  resource VARCHAR(512) NULL,
  project_id VARCHAR(128) NULL,
  observed_at DATETIME(6) NOT NULL,
  collected_at DATETIME(6) NOT NULL,
  observation_window_start DATETIME(6) NULL,
  observation_window_end DATETIME(6) NULL,
  freshness VARCHAR(16) NOT NULL,
  content JSON NOT NULL,
  provenance JSON NOT NULL,
  current_observation BOOLEAN NOT NULL DEFAULT TRUE,
  contradiction_status VARCHAR(32) NULL,
  content_digest VARCHAR(64) NOT NULL,
  created_at DATETIME(6) NOT NULL,
  updated_at DATETIME(6) NOT NULL,
  KEY idx_canonical_evidence_incident (tenant_id, incident_id, collected_at),
  KEY idx_canonical_evidence_requirement (tenant_id, requirement_id),
  KEY idx_canonical_evidence_content (content_digest)
);

CREATE TABLE IF NOT EXISTS evidence_rejections (
  rejection_id CHAR(36) NOT NULL PRIMARY KEY,
  tenant_id VARCHAR(128) NOT NULL,
  incident_id CHAR(36) NOT NULL,
  requirement_id CHAR(36) NOT NULL,
  job_id CHAR(36) NOT NULL,
  attempt_key VARCHAR(128) NOT NULL,
  record_index INT NOT NULL,
  reason_code VARCHAR(128) NOT NULL,
  reason_detail TEXT NULL,
  sanitized_record JSON NOT NULL,
  source_response_metadata JSON NOT NULL,
  created_at DATETIME(6) NOT NULL,
  updated_at DATETIME(6) NOT NULL,
  UNIQUE KEY uq_evidence_rejection_attempt (tenant_id, attempt_key, record_index),
  KEY idx_evidence_rejection_requirement (tenant_id, requirement_id, created_at)
);
