import { compactText, formatIstTimestamp, sourceChannelLabel, statusPillClass } from "../../appHelpers.jsx";
import { useRouteRuntime, type AlertStreamFilters } from "../../app/routeRuntime";

export default function AlertsRoute() {
  const { alerts } = useRouteRuntime();
  const updateFilter = (name: keyof AlertStreamFilters, value: string) => { alerts.setView(""); alerts.updateFilter(name, value); };
  return <section className="grid single-col ingestion-stream-page">
    <article className="ingestion-stream-hero"><div><span className="discovery-eyebrow">Live multi-source intake</span><h2>Alert Ingestion Stream</h2><p>Email, logs, Prometheus, Telemetry, and ticketing events as they land in KaiOps.</p></div><div className="ingestion-live-state"><span className={`ingestion-live-dot ${alerts.loading ? "is-loading" : ""} ${alerts.paused ? "is-paused" : ""}`} aria-hidden="true" /><div><strong>{alerts.paused ? "Live updates paused" : alerts.loading ? "Syncing now" : alerts.liveState === "connected" ? "Live · push connected" : alerts.liveState === "reconnecting" ? "Live reconnecting · polling fallback" : "Live · polling fallback"}</strong><small>{alerts.rows.length} of {alerts.totalRows} arrivals shown</small><small>Updated exactly: {alerts.updatedAt ? new Date(alerts.updatedAt).toLocaleString() : "not synced"}</small></div><button type="button" className="button-secondary" onClick={alerts.refresh} disabled={alerts.loading}>{alerts.loading ? "Refreshing..." : "Refresh now"}</button><button type="button" className="button-secondary" aria-pressed={alerts.paused} title={alerts.lastEventAt ? `Last push event ${alerts.lastEventAt}` : "No push event received yet"} onClick={alerts.togglePaused}>{alerts.paused ? "Resume live" : "Pause live"}</button></div></article>
    <article className="panel ingestion-control-panel"><div className="ingestion-section-tabs" role="tablist" aria-label="Alert lifecycle sections">{["active", "resolved", "failed", "historical"].map((section) => <button type="button" role="tab" aria-selected={alerts.section === section} className={`detail-tab ${alerts.section === section ? "active" : ""}`} key={section} onClick={() => { alerts.setSection(section); alerts.setView(""); }}>{section === "failed" ? "Failed Intake" : section.charAt(0).toUpperCase() + section.slice(1)}</button>)}</div><div className="ingestion-filter-grid">
      <label>Saved view<select value={alerts.view} onChange={(event) => event.target.value ? alerts.applyView(event.target.value) : alerts.setView("")}><option value="">Custom / all active</option>{alerts.savedViews.map((view) => <option key={view.id} value={view.id}>{view.label}</option>)}</select></label>
      <label>Time range<select value={alerts.filters.timeRange} onChange={(event) => updateFilter("timeRange", event.target.value)}><option value="1h">Last hour</option><option value="24h">Last 24 hours</option><option value="7d">Last 7 days</option><option value="all">All loaded</option></select></label>
      <label>Severity<select value={alerts.filters.severity} onChange={(event) => updateFilter("severity", event.target.value)}><option value="all">All severities</option><option value="critical">Critical</option><option value="high">High</option><option value="warning">Warning</option><option value="info">Info</option></select></label>
      <label>Application<select value={alerts.filters.application} onChange={(event) => updateFilter("application", event.target.value)}><option value="all">All applications</option><option value="selected">Current monitor</option><option value="assigned">Assigned only</option>{alerts.filterOptions.applications.map((application) => <option key={application} value={application.toLowerCase()}>{application}</option>)}</select></label>
      <label>Environment<select value={alerts.filters.environment} onChange={(event) => updateFilter("environment", event.target.value)}><option value="all">All environments</option>{alerts.filterOptions.environments.map((environment) => <option key={environment} value={environment}>{environment}</option>)}</select></label>
      <label className="ingestion-density-toggle"><input type="checkbox" checked={alerts.density === "compact"} onChange={(event) => alerts.setDensity(event.target.checked ? "compact" : "comfortable")} />Compact rows</label></div><p className="subtitle">Connector health is separate from alert count. Occurrence time and ingestion time are shown independently when supplied. Unsafe bulk mutations remain unavailable.</p></article>
    <div className="ingestion-channel-grid" aria-label="Alert source counts">{[["all", "ALL", "All arrivals"], ["prometheus", "PR", "Prometheus"], ["telemetry", "OT", "Telemetry"], ["email", "EM", "Email"], ["log", "LG", "Logs / OpenSearch"], ["ticket", "TK", "Tickets / Jira"], ["failed", "!", "Failed intake"]].map(([channel, icon, label]) => <button type="button" key={`stream-channel-${channel}`} className={`ingestion-channel-card channel-${channel} ${alerts.channel === channel ? "is-active" : ""}`} onClick={() => alerts.setChannel(channel)} aria-pressed={alerts.channel === channel}><span>{icon}</span><div><strong>{alerts.counts[channel] || 0}</strong><small>{label}</small></div></button>)}</div>
    <article className="panel ingestion-stream-panel"><div className="ingestion-stream-toolbar"><div><span className="discovery-eyebrow">Landing-pad events</span><h3>{alerts.channel === "all" ? "All source activity" : alerts.channel === "failed" ? "Failed ingestion activity" : `${sourceChannelLabel(alerts.channel)} activity`}</h3></div><label><span>Search stream</span><input value={alerts.query} onChange={(event) => alerts.setQuery(event.target.value)} placeholder="Alert, service, project, source, file" /></label></div>{alerts.error ? <p className="error">{alerts.error}</p> : null}<div className="ingestion-stream-list">
      {alerts.rows.map((row, index) => { const channel = row.source_channel || "prometheus"; const failed = String(row.status || "").toLowerCase() === "failed" || Boolean(row.error); return <article className={`ingestion-event channel-${channel} ${failed ? "is-failed" : ""}`} key={`${row.file || row.id || "arrival"}-${index}`}><div className="ingestion-event-marker"><span>{channel === "email" ? "EM" : channel === "log" ? "LG" : channel === "ticket" ? "TK" : channel === "telemetry" ? "OT" : "PR"}</span><i aria-hidden="true" /></div><div className="ingestion-event-main"><header><div><strong>{row.name || row.alert_name || "Unnamed alert"}</strong><span className={`source-badge source-${channel}`}>{sourceChannelLabel(channel)}</span><span className={`pill ${failed ? "status-failed" : statusPillClass(row.status || "processed")}`}>{row.status || "processed"}</span></div><time>{formatIstTimestamp(row.received_at || row.created_at || row.modified_at)}</time></header><p>{row.description || row.annotations?.description || row.error || "Alert received and normalized by the landing pad."}</p><footer><span><b>Service</b>{row.service || "-"}</span><span><b>Project</b>{row.application || row.project_name || row.project || "-"}</span><span><b>Severity</b>{String(row.severity || "-").toUpperCase()}</span><span title={row.file}><b>File</b>{compactText(row.file, 44)}</span><span><b>First seen</b>{formatIstTimestamp(row.first_seen || row.starts_at || row.created_at)}</span><span><b>Last seen</b>{formatIstTimestamp(row.last_seen || row.ends_at || row.updated_at || row.received_at)}</span><span><b>Occurrences</b>{row.occurrence_count || row.occurrences?.length || 1}</span><span><b>Owner</b>{row.assignee || row.owner || row.jira_assignee || "Unassigned"}</span></footer>{(row.deduplication_reason || row.correlation_reason || row.suppression_reason || row.maintenance_window) ? <details className="ingestion-reason"><summary>Why grouped or suppressed?</summary><p>{row.deduplication_reason || row.correlation_reason || row.suppression_reason || `Maintenance window: ${row.maintenance_window}`}</p></details> : null}{row.error ? <small className="ingestion-event-error">{row.error}</small> : null}</div></article>; })}
      {!alerts.rows.length && !alerts.loading ? <div className="ingestion-stream-empty"><strong>No arrivals match this view.</strong><p>Choose another source, clear the search, or verify that its connector is delivering events.</p></div> : null}
    </div></article>
  </section>;
}
