param(
    [string]$OutputFile = ".env.azure.foundry.generated",
    [bool]$AllowEmpty = $false
)

$ErrorActionPreference = "Stop"

function Get-RequiredEnv {
    param(
        [Parameter(Mandatory = $true)][string]$Name,
        [bool]$AllowEmptyValue = $false
    )

    $value = [Environment]::GetEnvironmentVariable($Name)
    if (-not $AllowEmptyValue -and [string]::IsNullOrWhiteSpace($value)) {
        throw "Environment variable '$Name' is required."
    }
    return $value
}

$RepoRoot = (Resolve-Path (Join-Path $PSScriptRoot "..")).Path
if (-not [System.IO.Path]::IsPathRooted($OutputFile)) {
    $OutputFile = Join-Path $RepoRoot $OutputFile
}

$databaseUrl = Get-RequiredEnv -Name "DATABASE_URL" -AllowEmptyValue $AllowEmpty
$serviceBusConnection = Get-RequiredEnv -Name "AZURE_SERVICE_BUS_CONNECTION_STRING" -AllowEmptyValue $AllowEmpty
$openAiEndpoint = Get-RequiredEnv -Name "AZURE_OPENAI_ENDPOINT" -AllowEmptyValue $AllowEmpty
$openAiKey = Get-RequiredEnv -Name "AZURE_OPENAI_API_KEY" -AllowEmptyValue $AllowEmpty
$embeddingsDeployment = Get-RequiredEnv -Name "AZURE_OPENAI_EMBEDDINGS_DEPLOYMENT" -AllowEmptyValue $AllowEmpty
$evaluationDeployment = Get-RequiredEnv -Name "AZURE_AI_EVALUATION_DEPLOYMENT" -AllowEmptyValue $AllowEmpty
$contentSafetyEndpoint = Get-RequiredEnv -Name "AZURE_CONTENT_SAFETY_ENDPOINT" -AllowEmptyValue $AllowEmpty
$contentSafetyApiKey = Get-RequiredEnv -Name "AZURE_CONTENT_SAFETY_API_KEY" -AllowEmptyValue $AllowEmpty
$azureMonitorConnection = Get-RequiredEnv -Name "AZURE_MONITOR_CONNECTION_STRING" -AllowEmptyValue $AllowEmpty

$lines = @(
    "# Generated by scripts/create-azure-foundry-env.ps1",
    "DATABASE_URL=$databaseUrl",
    "AZURE_SERVICE_BUS_CONNECTION_STRING=$serviceBusConnection",
    "AZURE_OPENAI_ENDPOINT=$openAiEndpoint",
    "AZURE_OPENAI_API_KEY=$openAiKey",
    "AZURE_OPENAI_EMBEDDINGS_DEPLOYMENT=$embeddingsDeployment",
    "AZURE_AI_EVALUATION_DEPLOYMENT=$evaluationDeployment",
    "AZURE_CONTENT_SAFETY_ENDPOINT=$contentSafetyEndpoint",
    "AZURE_CONTENT_SAFETY_API_KEY=$contentSafetyApiKey",
    "AZURE_MONITOR_CONNECTION_STRING=$azureMonitorConnection",
    "AZURE_SERVICE_BUS_ENABLED=true",
    "AZURE_CONTENT_SAFETY_ENABLED=true",
    "AZURE_OPENAI_EMBEDDINGS_ENABLED=true",
    "AZURE_AI_EVALUATION_ENABLED=true",
    "OBSERVABILITY_AZURE_MONITOR_ENABLED=true",
    "KAFKA_ENABLED=false",
    "EVENT_BUS_PROVIDER=azure-servicebus"
)

Set-Content -Path $OutputFile -Value ($lines -join [Environment]::NewLine) -Encoding utf8
Write-Host "Wrote $OutputFile" -ForegroundColor Green
